### ISSUE TITLE
Mes-secrets page

### ISSUE THREAD

**Issue by MelineeTS** [InseeFrLab/onyxia-web#161]
Too long to access to "mes-secrets"

**Comment by MelineeTS** [comment]
I have to refresh page to have mes-secrets page

**Comment by Donatien26** [comment]
I think it's because the header onyxia-region is not allowed in the vault's header allowed list.

In the console we could read : Blocage d’une requête multiorigines (Cross-Origin Request) : la politique « Same Origin » ne permet pas de consulter la ressource distante située sur https://vault.lab.sspcloud.fr/v1/sys/seal-status. Raison : l’en-tête « onyxia-region » n’est pas autorisé d’après l’en-tête « Access-Control-Allow-Headers » de la réponse de pré-vérification des requêtes CORS.
