### ISSUE TITLE
Wrong behaviour with a custom catalog

### ISSUE THREAD

**Issue by plugandplay** [InseeFrLab/onyxia-web#296]
Version of onyxia :
- web: 0.47.3
- api: 0.10

I created a custom catalog that I added to the chart next to the default one.
To access this custom catalog, I added a button to the side bar.

![image](https://user-images.githubusercontent.com/487306/161066390-baae8d60-8e4e-46f1-94ef-576d91bc8831.png)

When I click on the custom catalog link, it opens a new tab that shows my catalog but it is the default catalog button that is highlighted.

![image](https://user-images.githubusercontent.com/487306/161067171-afb4e0a8-3780-4e57-841f-e6a434ea638d.png)

From this tab, I can't go back to the default catalog anymore.epuis cet onglet.

**Comment by garronej** [comment]
I'm having a look

**Comment by marchufschmitt** [comment]
We can work on a first iteration to find a solution because this use case may come back (not often but still). We're not sure for the long term, but it may be an option now for you. What do you think about that?

Option 1 : A button to link to many other catalogs

<img width="837" alt="Capture d’écran 2022-03-31 à 16 02 13" src="https://user-images.githubusercontent.com/62331119/161082052-305f4b0b-09ac-4637-ab16-9823071aafec.png">
<img width="835" alt="Capture d’écran 2022-03-31 à 16 02 20" src="https://user-images.githubusercontent.com/62331119/161082078-07f4037d-1d02-44e6-9e79-39db77503a41.png">

Option 2 : A tab system to easily switch from one catalog to another

<img width="865" alt="Capture d’écran 2022-03-31 à 16 06 51" src="https://user-images.githubusercontent.com/62331119/161082113-bf511dfb-5d6b-4b7d-ab5e-233b5e92bcec.png">

**Comment by plugandplay** [comment]
It seems to be good alternatives. My feeling is that the first option is clearer but it's my opinion :)

**Comment by fcomte** [comment]
but it's 3 clicks to go to a service on an alternate catalogue

**Comment by garronej** [comment]
https://user-images.githubusercontent.com/6702424/161163218-d15a2a64-fb26-485a-b3c8-560c4f8a761d.mov

Option 2 has been implemented in v0.49.  

> It seems to be good alternatives. My feeling is that the first option is clearer but it's my opinion :)  

Agreed but the extra click would get old very quickly.  

[live](https://datalab.sspcloud.fr/catalog/inseefrlab-helm-charts-datascience)  

Only catalog in `"PROD"` states are listed.  

![image](https://user-images.githubusercontent.com/6702424/161163571-6efcd18a-2dbf-4405-b2e7-01a6a80bcd52.png)

Thank you for reaching out.
