### ISSUE TITLE
highligted charts

### ISSUE THREAD

**Issue by fcomte** [InseeFrLab/onyxia-web#359]
This feature help Onyxia Admins to highlight some chart inside a catalog.

When a user is on the catalog page : 
![image](https://user-images.githubusercontent.com/48868412/190599099-14f19a29-72bb-4bc4-8589-e9694beed3eb.png)

some charts are visible by default and some are not.
Onyxia-API shows this on the catalog endpoint with highlightedCharts attribut on each catalog.

This is not yet used by Onyxia-web. 
The onyxia-web env var should be deprecated because api send this information for each catalog now : 

```yaml
# OPTIONAL, Highlight some packages of the default catalog. It can also be used as a way of defining an ordering.
# For this result: https://user-images.githubusercontent.com/6702424/152658921-bb6e87ba-a9e0-4cbb-841c-baafd34f50ef.png
# you would use 
# HIGHLIGHTED_PACKAGES: |
# 	[ "rstudio", "jupyter", "ubuntu", "postgres", "code" ]
# The entries should correspond to the chart name, example with rstudio: https://github.com/InseeFrLab/helm-charts-datascience/blob/09dd37aca108423cb337a07be6a58f1cda381aa4/chart
# case doesn’t matter if an entry is not present in the catalog it doesn't matter.
# If not defined you'll directly get a view showing all available packages: https://user-images.githubusercontent.com/6702424/152658975-f3931d3f-b6bd-4b1c-a0c1-b35111ef4239.png
REACT_APP_HIGHLIGHTED_PACKAGES=
```

I think this new list of highligted charts must be an exact match.

**Comment by garronej** [comment]
This is a very interesting fist issue since it's rather simple but sill messes with the core and the ui.  

In other words, this would be droped:  
<img width="1171" alt="image" src="https://user-images.githubusercontent.com/6702424/190923183-08d04827-3a29-4365-aeb0-8435a33a3a87.png">

and this used instead:  
<img width="1314" alt="image" src="https://user-images.githubusercontent.com/6702424/190923206-f84cd599-7b4b-480b-b1dd-d177b0526b70.png">   



NOTE for self: It's a breaking change, update migration guide.
